export const UI_EVENTS = {
  // Navigation & General
  REROLL_REQUESTED: 'UI:REROLL_REQUESTED',
  RETURN_TO_SETUP: 'UI:RETURN_TO_SETUP',
  
  // Planet Selection
  PLANET_SELECTED: 'UI:PLANET_SELECTED',
  
  // Draft
  MECHANIC_SELECTED: 'UI:MECHANIC_SELECTED',
  
  // Combat
  COMBAT_ACTION_RESOLVE: 'UI:COMBAT_ACTION_RESOLVE',
  
  // Event
  EVENT_CHOICE_RESOLVE: 'UI:EVENT_CHOICE_RESOLVE',
  
  // Reward
  REWARD_CHOICE_SELECTED: 'UI:REWARD_CHOICE_SELECTED',
};
